const plants = [
  {
    id: "oak",
    name: "Дуб",
    rarity: "Обычное",
    rarityClass: "common",
    imgBig: "/oak.png",
    description: "Мощное дерево с густой кроной, символ устойчивости и силы. Создает ощущение надежности, спокойствия и уверенного роста.",
    type: "дерево",
  },
  {
    id: "sakura",
    name: "Сакура",
    rarity: "Легендарное",
    rarityClass: "legendary",
    imgBig: "/sakura.png",
    description: "Нежное дерево с розовыми цветами, символ весны и обновления. Наполняет сад гармонией и умиротворением.",
    type: "дерево",
  },
  {
    id: "birch",
    name: "Береза",
    rarity: "Обычная",
    rarityClass: "common",
    imgBig: "/birch.png",
    description: "Светлое дерево с тонким стволом и легкой листвой, символ чистоты и свежести. Делает атмосферу сада спокойной и живой.",
    type: "дерево",
  },
  {
    id: "willow",
    name: "Ива",
    rarity: "Редкое",
    rarityClass: "rare",
    imgBig: "/willow_big.png",
    description: "Плавное дерево со свисающими ветвями, символ тишины и созерцания. Придает саду мягкость, глубину и уютную задумчивость.",
    type: "дерево",
  },
  {
    id: "maple",
    name: "Клен",
    rarity: "Обычное",
    rarityClass: "common",
    imgBig: "/Maple-Tree-Silhouette-Against-Sunset-Sky-PNG.png",
    description: "Яркое дерево с резными листьями, символ перемен и внутренней энергии. Добавляет саду насыщенность, тепло и выразительность.",
    type: "дерево",
  },
  {
    id: "pine",
    name: "Сосна",
    rarity: "Обычное",
    rarityClass: "common",
    imgBig: "/pine.png",
    description: "Высокое хвойное дерево с устойчивым силуэтом, символ выносливости и спокойствия. Наполняет сад свежестью, стабильностью и простором.",
    type: "дерево",
  },
  {
    id: "spruce",
    name: "Ель",
    rarity: "Редкое",
    rarityClass: "rare",
    imgBig: "/Spruce-Tree-Surrounded-By-Wildflower-PNG.png",
    description: "Стройное хвойное дерево с плотными ветвями, символ защиты и собранности. Делает пространство сада более цельным и глубоким.",
    type: "дерево",
  },
  {
    id: "lavender",
    name: "Лаванда",
    rarity: "Обычная",
    rarityClass: "common",
    imgBig: "/Lavender-PNG-Photo-Image.png",
    description: "Ароматное растение с фиолетовыми соцветиями, символ покоя и легкости. Наполняет сад ощущением свежести, уюта и мягкой гармонии.",
    type: "цветок",
  },
  {
    id: "rose",
    name: "Роза",
    rarity: "Редкое",
    rarityClass: "rare",
    imgBig: "/Rose-PNG.png",
    description: "Элегантный цветок с выразительными лепестками, символ красоты и силы чувств. Придает саду яркость, изящество и особый шарм.",
    type: "цветок",
  },
  {
    id: "lotus",
    name: "Лотос",
    rarity: "Легендарное",
    rarityClass: "legendary",
    imgBig: "/Lotus-Flower-PNG-Image.png",
    description: "Утонченный водный цветок, символ чистоты и внутреннего роста. Наполняет сад ощущением тишины, баланса и светлого обновления.",
    type: "цветок",
  },
  {
    id: "sunflower",
    name: "Подсолнух",
    rarity: "Обычная",
    rarityClass: "common",
    imgBig: "/sunflower.png",
    description: "Яркий высокий цветок, тянущийся к свету, символ радости и жизненной энергии. Делает сад солнечным, теплым и дружелюбным.",
    type: "цветок",
  },
  {
    id: "fern",
    name: "Папоротник",
    rarity: "Редкое",
    rarityClass: "rare",
    imgBig: "/Fern-Branch-Free-PNG.png",
    description: "Пышное растение с резными листьями, символ тайны и природной глубины. Добавляет саду лесную атмосферу, мягкость и живую фактуру.",
    type: "растение",
  },
  {
    id: "bamboo",
    name: "Бамбук",
    rarity: "Эпическое",
    rarityClass: "epic",
    imgBig: "/Bamboo-PNG-Picture.png",
    description: "Гибкое и стройное растение, символ роста и внутренней устойчивости. Делает сад легким, современным и наполненным движением.",
    type: "растение",
  },
  {
    id: "cactus",
    name: "Кактус",
    rarity: "Обычное",
    rarityClass: "common",
    imgBig: "/Cactus-PNG-7-1.png",
    description: "Компактное растение с сильным характером, символ выживания и самостоятельности. Добавляет саду оригинальность и необычную выразительность.",
    type: "растение",
  },
  {
    id: "orchid",
    name: "Орхидея",
    rarity: "Эпическое",
    rarityClass: "epic",
    imgBig: "/Orchids-PNG-Image.png",
    description: "Изысканный цветок с утонченной формой, символ редкой красоты и хрупкой силы. Наполняет сад элегантностью, нежностью и особой атмосферой.",
    type: "цветок",
  },
];

export default plants;