const plants = [
  {
    id: "birch",
    name: "Береза",
    rarity: "Обычная",
    rarityClass: "common",
    imgBig: "/birch_big.png",
    description: "Светлое дерево с тонким стволом и легкой листвой. Создает ощущение чистоты, свежести и спокойного роста.",
    type: "дерево",
  },
  {
    id: "ginkgo",
    name: "Гинкго",
    rarity: "Эпическое",
    rarityClass: "epic",
    imgBig: "/ginko_big.png",
    description: "Древнее дерево с веерообразными листьями и теплым золотистым оттенком. Добавляет саду редкость, благородство и ощущение долголетия.",
    type: "дерево",
  },
  {
    id: "maple_japan",
    name: "Японский клен",
    rarity: "Редкое",
    rarityClass: "rare",
    imgBig: "/maple_japan_big.png",
    description: "Яркое декоративное дерево с насыщенной красной листвой. Делает сад выразительным, живым и особенно атмосферным.",
    type: "дерево",
  },
  {
    id: "oak",
    name: "Дуб",
    rarity: "Редкое",
    rarityClass: "rare",
    imgBig: "/oak_big.png",
    description: "Мощное дерево с широкой кроной, символ устойчивости и силы. Наполняет пространство надежностью, глубиной и спокойствием.",
    type: "дерево",
  },
  {
    id: "orchid",
    name: "Орхидея",
    rarity: "Эпическая",
    rarityClass: "epic",
    imgBig: "/orchids_big.png",
    description: "Изящный цветок с мягкими розовыми лепестками. Придает саду нежность, утонченность и ощущение редкой красоты.",
    type: "цветок",
  },
  {
    id: "rose",
    name: "Роза",
    rarity: "Редкая",
    rarityClass: "rare",
    imgBig: "/roses_big.png",
    description: "Пышный куст с множеством розовых бутонов. Делает сад более ярким, романтичным и декоративным.",
    type: "цветок",
  },
  {
    id: "sakura",
    name: "Сакура",
    rarity: "Легендарное",
    rarityClass: "legendary",
    imgBig: "/sakura_big.png",
    description: "Нежное дерево с облаком розовых цветов, символ весны и обновления. Наполняет сад гармонией, легкостью и особой атмосферой.",
    type: "дерево",
  },
  {
    id: "thuja",
    name: "Туя",
    rarity: "Обычная",
    rarityClass: "common",
    imgBig: "/tuya_big.png",
    description: "Стройное хвойное растение с аккуратным силуэтом. Добавляет саду свежесть, порядок и спокойную зелень.",
    type: "дерево",
  },
  {
    id: "willow",
    name: "Ива",
    rarity: "Легендарное",
    rarityClass: "legendary",
    imgBig: "/willow_big.png",
    description: "Высокое дерево со свисающими ветвями и мягким силуэтом. Делает атмосферу сада глубокой, тихой и немного сказочной.",
    type: "дерево",
  },
];

export default plants;
